### ISSUE TITLE
Add CircleCI integration to allow documentation building 

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/nightlights-internal#7]
@dereklieu Can you to enable CircleCI integration for the repos `wbg-bigdata/global-nightlights-*`? I've setup doc-seed at `gh-pages` branch and this is a step needed to build documentation.

**Comment by dereklieu** [comment]
I actually don't have the admin privileges to do that. @vgeorge could you use something like the `gh-pages` npm module to do this push manually?

**Comment by vgeorge** [comment]
We've setup up manual publishing with `gh-pages` module.
